import type { Metadata } from "next";
import { Roboto, Noto_Sans_Tamil } from "next/font/google";
// Tailwind setup + design tokens
import "@/styles/globals.css";
// SCSS architecture (7-1 or modules)
import "@/styles/main.scss";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-roboto",
});

const notoSansTamil = Noto_Sans_Tamil({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-noto-sans-tamil",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} ${notoSansTamil.variable}`}
        suppressHydrationWarning
      >
        {children}
      </body>
    </html>
  );
}
